//! Floer homology basics: Morse theory on loop spaces.

use nalgebra::DVector;
use serde::{Deserialize, Serialize};

/// Floer homology is an infinite-dimensional analog of Morse homology
/// applied to the action functional on the loop space of a symplectic manifold.
///
/// Key ideas:
/// - Critical points of the action functional = periodic Hamiltonian orbits
/// - Connecting trajectories = solutions of Floer's equation (perturbed J-holomorphic cylinders)
/// - HF*(φ) = chain complex generated by fixed points of φ

/// A critical point (periodic orbit) of the action functional.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FloerCriticalPoint {
    /// Position (fixed point of the Hamiltonian symplectomorphism)
    pub position: Vec<f64>,
    /// Action value (evaluation of action functional)
    pub action: f64,
    /// Conley-Zehnder index (grading for Floer homology)
    pub cz_index: i32,
}

/// A Floer trajectory connecting two critical points.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FloerTrajectory {
    /// Starting critical point index
    pub from_index: usize,
    /// Ending critical point index
    pub to_index: usize,
    /// Energy of the trajectory
    pub energy: f64,
}

/// Floer chain complex.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FloerComplex {
    /// Critical points (generators)
    pub generators: Vec<FloerCriticalPoint>,
    /// Trajectories (differential)
    pub trajectories: Vec<FloerTrajectory>,
    /// Grading range
    pub min_index: i32,
    pub max_index: i32,
}

impl FloerComplex {
    /// Create an empty Floer complex.
    pub fn new() -> Self {
        Self {
            generators: Vec::new(),
            trajectories: Vec::new(),
            min_index: 0,
            max_index: 0,
        }
    }

    /// Add a critical point (periodic orbit).
    pub fn add_critical_point(&mut self, position: Vec<f64>, action: f64, cz_index: i32) -> usize {
        let idx = self.generators.len();
        if idx == 0 || cz_index < self.min_index {
            self.min_index = cz_index;
        }
        if idx == 0 || cz_index > self.max_index {
            self.max_index = cz_index;
        }
        self.generators.push(FloerCriticalPoint { position, action, cz_index });
        idx
    }

    /// Add a Floer trajectory (differential).
    pub fn add_trajectory(&mut self, from: usize, to: usize, energy: f64) {
        self.trajectories.push(FloerTrajectory {
            from_index: from,
            to_index: to,
            energy,
        });
    }

    /// Compute the boundary operator ∂: CF_k → CF_{k-1}.
    /// Returns a matrix representing ∂ over Z/2.
    pub fn boundary_matrix(&self, k: i32) -> Vec<Vec<u8>> {
        let source: Vec<usize> = self.generators.iter()
            .enumerate()
            .filter(|(_, g)| g.cz_index == k)
            .map(|(i, _)| i)
            .collect();
        let target: Vec<usize> = self.generators.iter()
            .enumerate()
            .filter(|(_, g)| g.cz_index == k - 1)
            .map(|(i, _)| i)
            .collect();

        let mut matrix = vec![vec![0u8; target.len()]; source.len()];
        for traj in &self.trajectories {
            if let (Some(si), Some(ti)) = (
                source.iter().position(|&i| i == traj.from_index),
                target.iter().position(|&i| i == traj.to_index),
            ) {
                matrix[si][ti] ^= 1; // Z/2 addition
            }
        }
        matrix
    }

    /// Compute the rank of the boundary matrix over Z/2.
    fn rank_z2(matrix: &[Vec<u8>]) -> usize {
        if matrix.is_empty() { return 0; }
        let m = matrix.len();
        let n = matrix[0].len();
        let mut mat: Vec<Vec<u8>> = matrix.to_vec();
        let mut rank = 0;
        for col in 0..n {
            // Find pivot
            let pivot = (rank..m).find(|&r| mat[r][col] == 1);
            if let Some(p) = pivot {
                mat.swap(rank, p);
                for r in 0..m {
                    if r != rank && mat[r][col] == 1 {
                        for c in 0..n {
                            mat[r][c] ^= mat[rank][c];
                        }
                    }
                }
                rank += 1;
            }
        }
        rank
    }

    /// Compute Floer homology HF_k over Z/2.
    /// HF_k = ker(∂_k) / im(∂_{k+1}).
    pub fn compute_homology(&self, k: i32) -> usize {
        let k_dim = self.generators.iter().filter(|g| g.cz_index == k).count();
        let d_k = self.boundary_matrix(k);
        let d_k1 = self.boundary_matrix(k + 1);
        let rank_dk = Self::rank_z2(&d_k);
        let rank_dk1 = Self::rank_z2(&d_k1);
        // dim(HF_k) = dim(CF_k) - rank(∂_k) - rank(∂_{k+1})
        k_dim - rank_dk - rank_dk1
    }

    /// Total rank of Floer homology.
    pub fn total_rank(&self) -> usize {
        let mut total = 0;
        for k in self.min_index..=self.max_index {
            total += self.compute_homology(k);
        }
        total
    }
}

impl Default for FloerComplex {
    fn default() -> Self {
        Self::new()
    }
}

/// Conley-Zehnder index for a periodic orbit.
/// For the standard harmonic oscillator at level n: CZ = 2n.
pub fn conley_zehnder_index(harmonic_level: usize) -> i32 {
    2 * harmonic_level as i32
}

/// Build a Floer complex for the harmonic oscillator H = Σ ω_i(|z_i|²/2).
pub fn harmonic_oscillator_complex(n_modes: usize, max_level: usize) -> FloerComplex {
    let mut complex = FloerComplex::new();
    for level in 0..=max_level {
        for mode in 0..n_modes {
            let pos = vec![0.0; 2 * n_modes];
            let cz = conley_zehnder_index(level);
            let action = (level + 1) as f64;
            complex.add_critical_point(pos, action, cz);
        }
    }
    complex
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_empty_complex() {
        let c = FloerComplex::new();
        assert_eq!(c.total_rank(), 0);
    }

    #[test]
    fn test_simple_complex_no_differential() {
        let mut c = FloerComplex::new();
        c.add_critical_point(vec![0.0], 1.0, 0);
        c.add_critical_point(vec![1.0], 2.0, 1);
        // No trajectories → homology = all generators
        assert_eq!(c.compute_homology(0), 1);
        assert_eq!(c.compute_homology(1), 1);
    }

    #[test]
    fn test_complex_with_differential() {
        let mut c = FloerComplex::new();
        c.add_critical_point(vec![0.0], 1.0, 0);
        let idx1 = c.add_critical_point(vec![1.0], 2.0, 1);
        c.add_critical_point(vec![2.0], 3.0, 0);
        c.add_trajectory(idx1, 0, 1.0);
        // ∂(gen_1) = gen_0, so HF_0 = (gen_0 + gen_2) / im = 1 generator
        assert_eq!(c.compute_homology(0), 1);
    }

    #[test]
    fn test_conley_zehnder_index() {
        assert_eq!(conley_zehnder_index(0), 0);
        assert_eq!(conley_zehnder_index(1), 2);
        assert_eq!(conley_zehnder_index(3), 6);
    }

    #[test]
    fn test_boundary_matrix_empty() {
        let c = FloerComplex::new();
        let m = c.boundary_matrix(0);
        assert!(m.is_empty());
    }

    #[test]
    fn test_rank_z2() {
        let m = vec![vec![1, 0], vec![0, 1]];
        assert_eq!(FloerComplex::rank_z2(&m), 2);
        let m2 = vec![vec![1, 0], vec![1, 0]];
        assert_eq!(FloerComplex::rank_z2(&m2), 1);
    }

    #[test]
    fn test_harmonic_oscillator_complex() {
        let c = harmonic_oscillator_complex(1, 3);
        assert_eq!(c.generators.len(), 4); // levels 0,1,2,3, one mode each
    }

    #[test]
    fn test_add_critical_points() {
        let mut c = FloerComplex::new();
        c.add_critical_point(vec![0.0, 0.0], 1.0, 0);
        c.add_critical_point(vec![1.0, 0.0], 2.0, 1);
        c.add_critical_point(vec![0.0, 1.0], 1.5, -1);
        assert_eq!(c.generators.len(), 3);
        assert_eq!(c.min_index, -1);
        assert_eq!(c.max_index, 1);
    }

    #[test]
    fn test_trajectories() {
        let mut c = FloerComplex::new();
        let i0 = c.add_critical_point(vec![0.0], 1.0, 0);
        let i1 = c.add_critical_point(vec![1.0], 2.0, 1);
        let i2 = c.add_critical_point(vec![2.0], 3.0, 2);
        c.add_trajectory(i2, i1, 1.0);
        c.add_trajectory(i1, i0, 1.0);
        assert_eq!(c.trajectories.len(), 2);
    }
}
